#ifndef CHIPCOMMS_SPIS_DEVICE_H
#define CHIPCOMMS_SPIS_DEVICE_H

#define SPI0_RX_PIN PICO_DEFAULT_SPI_RX_PIN
#define SPI0_TX_PIN PICO_DEFAULT_SPI_TX_PIN
#define SPI0_SCK_PIN PICO_DEFAULT_SPI_SCK_PIN
#define SPI0_CSN_PIN PICO_DEFAULT_SPI_CSN_PIN
void spi_read_task(void* args);

#endif
